vList = ['UIDragItem','UITableViewCellContentView', 'UIPageControl','UIAlertView', 'UIViewController',
         'UIToolbar','UILabel','UIScrollView', 'UISwitch', 'UITabBarItem','UIAlertController', 'UISearchController',
         'UIPushBehavior', 'UIPickerView', 'UIMotionEffectGroup', 'UIInputView','UIGravityBehavior',
          'UITableViewHeaderFooterView', 'UISearchDisplayController',
         'UIAccessibilityCustomAction', 'UIAlertAction',  'UIStackView', 'UISlider',
         'UIFocusGuide', 'UIDropProposal', 'UICollectionViewCell', 'UILongPressGestureRecognizer', 'UIButton',
         'UIPresentationController', 'UIPrintInteractionController', 'UIApplication', 'UIWebView', 'UIVisualEffectView',
         'UIRotationGestureRecognizer', 'UIBezierPath', 'UIPrintInfo', 'UITapGestureRecognizer', 'UITableViewController',
         'UIAttachmentBehavior', 'UIBarItem', 'UIBarButtonItem', 'UICollectionViewTransitionLayout',
          'UISplitViewController', 'UISearchBar', 'UIInterpolatingMotionEffect',
         'UIFieldBehavior', 'UIPasteboard', 'UIKeyCommand', 'UIActivityIndicatorView',
         'UICollectionViewLayoutInvalidationContext', 'UIAccelerometer', 'UIDynamicAnimator',  'UIStepper',
         'UITextField', 'UIMarkupTextPrintFormatter', 'UIImageView', 'UITextChecker', 'UIProgressView', 'UIPrintFormatter',
         'UISnapBehavior', 'UIDragPreviewParameters', 'UIWindow', 'UIViewPropertyAnimator',
         'UIInputViewController', 'UIDatePicker', 'UINavigationBar', 'UIPinchGestureRecognizer', 'UILayoutGuide',
         'UIPrinterPickerController', 'UIAccessibilityElement', 'UIPasteConfiguration', 'UIPopoverPresentationController',
         'UIRefreshControl', 'UIImagePickerController', 'UIDragInteraction', 'UISegmentedControl', 'UIPopoverController',
         'UITabBar', 'UINavigationController',  'UISwipeGestureRecognizer', 'UITableViewCell',
         'UITextView', 'UIVideoEditorController', 'UIPopoverBackgroundView', 'UITabBarController', 'UICollectionView',
         'UIPanGestureRecognizer', 'UIMenuController', 'UIGraphicsPDFRendererFormat', 'UIGestureRecognizer',
         'UICollectionViewLayoutAttributes', 'UIContextualAction', 'UIDropInteraction', 'UICollectionViewController',
         'UIActivityViewController', 'UICloudSharingController', 'UIMenuItem', 'UITableView', 'UITableViewRowAction',
         'UICollisionBehavior', 'UIActionSheet', 'UIPageViewController', 'UIControl', 'UINavigationItem', 'UIPrintPageRenderer',
         'UISwipeActionsConfiguration', 'UIAccessibilityCustomRotorSearchPredicate', 'UISearchController', 'UIAlertController',
         'UITabBarItem',  'UIPercentDrivenInteractiveTransition', 'UITextDropProposal',
         'UIScrollView', 'UISwitch', 'UILabel',  'UIDynamicItemBehavior', 'UIPreviewInteraction',
         'UITextInputAssistantItem', 'UIToolbar', 'UIScreen', 'UIViewController', 'UIAlertView',
         'UIGraphicsImageRendererFormat', 'UIAccessibilityCustomRotor', 'UICollectionViewFlowLayout', 'UIResponder',
         'UIBarButtonItemGroup', 'UICollectionViewFlowLayoutInvalidationContext', 'UIAccessibilityCustomRotorItemResult',
         'UIPageControl', 'UIDragItem', 'UIScreenEdgePanGestureRecognizer',
         'UISplitViewController', 'UICollectionViewTransitionLayout', 'UITableViewController', 'UIAttachmentBehavior',
         'UITapGestureRecognizer', 'UIPrintInfo', 'UIBarItem', 'UIBarButtonItem', 'UIRotationGestureRecognizer', 'UIBezierPath',
         'UIApplication', 'UIVisualEffectView', 'UIWebView', 'UIPrintInteractionController', 'UIPresentationController',
         'UIButton', 'UILongPressGestureRecognizer', 'UICollectionViewCell', 'UIDropProposal',
          'UIStackView', 'UISlider', 'UIFocusGuide', 'UIAlertAction', 'UIView',
         'UITableViewHeaderFooterView',  'UIAccessibilityCustomAction', 'UISearchDisplayController',
         'UIManagedDocument', 'UIGravityBehavior', 'UIPushBehavior', 'UIPickerView', 'UIMotionEffectGroup', 'UIInputView',
         'UIImagePickerController', 'UIDragInteraction', 'UISegmentedControl', 'UIPopoverPresentationController',
         'UIRefreshControl', 'UIAccessibilityElement', 'UIPasteConfiguration', 'UIPinchGestureRecognizer', 'UINavigationBar',
         'UIPrinterPickerController', 'UILayoutGuide', 'UIViewPropertyAnimator',
         'UIInputViewController', 'UIDatePicker', 'UIDragPreviewParameters', 'UIWindow', 'UISnapBehavior', 'UIProgressView',
         'UIPrintFormatter', 'UITextChecker', 'UIImageView', 'UIStepper', 'UIMarkupTextPrintFormatter',
         'UITextField', 'UIDynamicAnimator', 'UIActivityIndicatorView', 'UIAccelerometer',
         'UICollectionViewLayoutInvalidationContext', 'UIKeyCommand', 'UIPasteboard', 'UISearchBar',
         'UIInterpolatingMotionEffect', 'UIFieldBehavior', 'UIPrintPageRenderer', 'UIAccessibilityCustomRotorSearchPredicate',
         'UISwipeActionsConfiguration', 'UIControl', 'UIPageViewController', 'UINavigationItem', 'UITableViewRowAction',
         'UICollisionBehavior', 'UIActionSheet', 'UIMenuItem', 'UITableView', 'UIActivityViewController',
         'UICloudSharingController', 'UICollectionViewController', 'UIDropInteraction', 'UICollectionViewLayoutAttributes',
         'UIContextualAction', 'UIGraphicsPDFRendererFormat', 'UIGestureRecognizer', 'UIPanGestureRecognizer',
         'UICollectionView', 'UITabBarController', 'UIMenuController', 'UITextView', 'UIPopoverBackgroundView',
         'UIVideoEditorController', 'UISwipeGestureRecognizer', 'UITableViewCell', 'UINavigationController',
          'UIPopoverController', 'UITabBar', 'UIView']
